image: ralfjung/opam-ci:latest

iris-coq8.5.3:
  tags:
  - fp-timing
  script:
  # prepare
  - . build/opam-ci.sh 'coq 8.5.3' 'coq-mathcomp-ssreflect 1.6.1'
  # build
  - 'time make -j8 TIMED=y 2>&1 | tee build-log.txt'
  - 'if fgrep Axiom build-log.txt >/dev/null; then exit 1; fi'
  - 'cat build-log.txt | egrep "[a-zA-Z0-9_/-]+ \(user: [0-9]" | tee build-time.txt'
  - 'if (( RANDOM % 10 == 0 )); then make validate; fi'
  cache:
    key: "coq8.5.3"
    paths:
    - opamroot/
  only:
  - iris-3.0
  artifacts:
    paths:
    - build-time.txt

iris-coq8.6:
  tags:
  - fp-timing
  script:
  # prepare
  - . build/opam-ci.sh 'coq 8.6' 'coq-mathcomp-ssreflect 1.6.1'
  # build
  - 'time make -j8'
  cache:
    key: "coq8.6"
    paths:
    - opamroot/
  only:
  - iris-3.0
