image: ralfjung/opam-ci:latest

stages:
  - build

variables:
  CPU_CORES: "10"
  MAIN_BRANCH: "master"
  GIT_SUBMODULE_STRATEGY: "recursive"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - opamroot/
  only:
  - "$MAIN_BRANCH"
  - /^ci/
  except:
  - triggers
  - schedules

## Build jobs

build-coq.dev:
  <<: *template
  variables:
    OPAM_PINS: "coq version dev   coq-mathcomp-ssreflect version dev"
    VALIDATE: "1"

build-coq.8.7.2:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.7.2   coq-mathcomp-ssreflect version 1.6.4"
    OPAM_PKG: "coq-iris"
    TIMING_PROJECT: "iris"
    TIMING_CONF: "coq-8.7.2"
  tags:
  - fp-timing

build-coq.8.7.1:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.7.1   coq-mathcomp-ssreflect version 1.6.4"

build-coq.8.7.0:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.7.0   coq-mathcomp-ssreflect version 1.6.4"

build-coq.8.6.1:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.6.1   coq-mathcomp-ssreflect version 1.6.4"

build-stdpp.dev:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.7.2   coq-mathcomp-ssreflect version 1.6.4   coq-stdpp.dev git https://gitlab.mpi-sws.org/robbertkrebbers/coq-stdpp/#$STDPP_REV"
  except:
  only:
  - triggers
  - schedules
