image: ralfjung/opam-ci:latest

stages:
  - build

variables:
  CPU_CORES: "10"
  GIT_SUBMODULE_STRATEGY: "recursive"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - opamroot/
  only:
  - gen_proofmode
  - /^ci/
  except:
  - triggers
  - schedules

## Build jobs

build-coq.dev:
  <<: *template
  variables:
    BUILD_TARGET: "ref" # don't check test output
    OPAM_PINS: "coq version dev"
    VALIDATE: "1"

build-coq.8.8.dev:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.8.dev"

build-coq.8.8.0:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.8.0"
    OPAM_PKG: "coq-iris"
    OPAM_PKG_BRANCH: "gen_proofmode"
    TIMING_PROJECT: "iris"
    TIMING_CONF: "coq-8.8.0"
  tags:
  - fp-timing

build-coq.8.7.2:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.7.2"

build-coq.8.7.1:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.7.1"
