image: ralfjung/opam-ci:opam2

stages:
  - build

variables:
  CPU_CORES: "10"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - git clone https://gitlab.mpi-sws.org/FP/iris-ci.git ci -b opam2
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME-iris-3.1"
    paths:
    - opamroot/
  only:
  - iris-3.1
  - /^ci/
  except:
  - triggers
  - schedules

## Build jobs

build-coq.8.8.1:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.8.1   coq-mathcomp-ssreflect version 1.7.0"
    TIMING_PROJECT: "iris"
    TIMING_CONF: "coq-8.8.1"
  tags:
  - fp-timing

build-coq.8.8.0:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.8.0   coq-mathcomp-ssreflect version 1.7.0"

build-coq.8.7.1:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.7.1   coq-mathcomp-ssreflect version 1.6.4"

build-coq.8.7.0:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.7.0   coq-mathcomp-ssreflect version 1.6.4"

build-coq.8.6.1:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.6.1   coq-mathcomp-ssreflect version 1.6.4"
